### PR TITLE
Rephrases intro sentence of Cascading section.

### PR DESCRIPTION
**Pull request by dogonthehorizon**
I'm hoping that the rephrasing of this sentence makes the paragraph flow a little better and that I captured the original intention of the author.

### CODE REVIEW

**Comment by jonathanong** [comment]
haha wow. missed the cascading part. i think we can get rid of the "method" in "node's method of callbacks". i think `node's callbacks` sounds better. plus, it isn't just node - also js. maybe `javascript callbacks?`

**Comment by tj** [comment]
yeah method of callbacks sounds weird but other than that LGTM, "node's use of callbacks"

**Comment by dogonthehorizon** [comment]
Hopefully that should do it!

**Comment by tj** [comment]
oh just realized this is the wrong repo

**Comment by tj** [comment]
meh I kinda prefer what we had anyway to be honest, it's not that it was hard before, just hard to make it not suck (user friendly)

**Comment by tj** [comment]
updated it a little in koa's md

**Pull request merged**
