### PR TITLE
Makefile: build faster

### PR DESCRIPTION
**Pull request by jonathanong**
any reason you don't do this? waiting is pretty annoying to me.

### CODE REVIEW

**Comment by tj** [comment]
they should be deps so the freshness propagates, -j at the top level

**Comment by tj** [comment]
I believe you can also specify JOBS= or something as an env var

**Comment by jonathanong** [comment]
meh. i actually like everything rebuilding. don't really like `make clean`.

**Comment by tj** [comment]
that's the point of make though, it checks the mtimes and only builds when it needs to, but you can do `make clean build` etc if you always want to clobber

**Pull request closed without merging**
