### PR TITLE
update to newest versin, add slack 

### PR DESCRIPTION
**Pull request by Pana**
FYI

### CODE REVIEW

**Comment by jonathanong** [comment]
@koajs/owners @koajs/devs anyone using slack?

**Comment by mgol** [comment]
Node.js 4 is out so this PR is a little outdated now. However, the site is even more outdated. ;)

**Comment by tj** [comment]
oops I never saw this, updated but no slack, adding that sounds good!

**Comment by jonathanong** [comment]
sorry this got ignored. noticed that the repo is deleted and there are merge conflicts, so closing for now. ping me on twitter if anyone thinks we need to rebuild

**Pull request closed without merging**
